export enum PageRoutes {
  HOME = '/',
  BLOG = '/blog',
}

export enum SocialRoutes {
  EMAIL = 'mailto:deanp21@gmail.com',
}

export enum ExternalRoutes {
  AI_HUB = 'https://hub-ai.netlify.app/',
  AMPLITUDE = 'https://amplitude.com/',
  A_STAR = 'https://en.wikipedia.org/wiki/A*_search_algorithm',
  AUGMENTED_REALITY = 'https://en.wikipedia.org/wiki/Augmented_reality',
  AWS = 'https://aws.amazon.com/',
  AWS_CLOUD9 = 'https://aws.amazon.com/cloud9/',
  AWS_EC2 = 'https://aws.amazon.com/ec2/',
  AWS_LAMBDA = 'https://aws.amazon.com/lambda/',
  AWS_REKOGNITION = 'https://aws.amazon.com/rekognition/',
  AWS_S3 = 'https://aws.amazon.com/s3/',
  BFS = 'https://en.wikipedia.org/wiki/Breadth-first_search',
  CHAKRA_UI = 'https://chakra-ui.com/',
  DFS = 'https://en.wikipedia.org/wiki/Depth-first_search',
  EXPRESS = 'https://expressjs.com/',
  EIGHT_PUZZLE = 'https://en.wikipedia.org/wiki/sliding_puzzle',
  FIGMA = 'https://www.figma.com/',
  JEST = 'https://jestjs.io/',
  MATERIAL_UI = 'https://material-ui.com/',
  MIXPANEL = 'https://mixpanel.com/',
  NEXT = 'https://nextjs.org/',
  NODE = 'https://nodejs.org/en/',
  NPM = 'https://www.npmjs.com/',
  OFFICE_365 = 'https://www.office.com/',
  POSTGRESQL = 'https://www.postgresql.org/',
  PUG = 'https://pugjs.org/api/getting-started.html',
  PYTHON = 'https://www.python.org/',
  REACT = 'https://reactjs.org/',
  ROLLUP = 'https://rollupjs.org/',
  SANITY = 'https://www.sanity.io/',
  SCOTTPHS = 'https://scottphs.com/',
  SEGNA = 'https://segna.io/',
  SENTRY = 'https://sentry.io/',
  STORYBOOK = 'https://storybook.js.org/',
  TYPESCRIPT = 'https://www.typescriptlang.org/',
  WEBFLOW = 'https://webflow.com/',
  VITE = 'https://vitejs.dev/',
}
